settingsSecrets:
    secretKey: ENC[AES256_GCM,data:AclFquStDrW2HxpmCo3IqhFNC10wX5wuNaXLiOmv0E0LsvlYRqpLRwA7W8ZwhCJioVA=,iv:1HN0H/prTO7qj4lXWIbSWH4gU5M5H3/ZRsQLqriVhXM=,tag:1Vukyf+TUL94o5ehpee6IQ==,type:str]
    allowedHost: ENC[AES256_GCM,data:FMTQuzMbGDkSXSADaGDw7ICiyg==,iv:0OlY3QxogwEKBrQSPuBANNyzuBTz+9n7qhK28gQ0g04=,tag:LUDXJrnmusqjnTIZ2Ehbfg==,type:str]
postgresql:
    global:
        postgresql:
            postgresqlDatabase: ENC[AES256_GCM,data:0RFaPQ==,iv:kistBnmd0ZBjcos2MBOcXWBfQTNUy+QR1s+yJj6MW5Q=,tag:0B0GL9nGK+mEevea3eWsRw==,type:str]
            postgresqlUsername: ENC[AES256_GCM,data:9H3cyA==,iv:NCxL7+QhjvHRrQ0f+5nOOtBqB4F5dF4E2UEOx837blI=,tag:r+CS5xfd401ZeGfKKe0A4Q==,type:str]
            postgresqlPassword: ENC[AES256_GCM,data:dbPDh8PPmjdInHuiq01M0O2o00P9Eq8pN1s=,iv:MbbUGEx4aramdL17O9CkBaboKxC1Qx00r6Vq6AK2+20=,tag:Iy+tJI8Tr9TgZcLl/qiKkQ==,type:str]
image:
    repository: ENC[AES256_GCM,data:XL1L3+nTqc66Y5XZkeeY5jkyGsYEo4Q26MYB1A==,iv:nqnvXsQeGJ8oHmYO9oMQUFT/eWH6cnaJARiJjxnpq48=,tag:F4zTxQ+/FMhau03z3eIRYw==,type:str]
    pullPolicy: ENC[AES256_GCM,data:QjB+Rhhe6tg2aO5N,iv:aLolRKNj1goj8C1zXqorTNMiul0GAiNpuql/TfJp2F0=,tag:16Tn0T0Hz1cLCA/P12E4wg==,type:str]
    #ENC[AES256_GCM,data:2LJRPDPCL/MwT3r5OELR1eg0U34bmJsOR6gVB4iyRVjOpiX5PCIpdhVIOV1giKWlLIc4Q3h8Q+/ZGi1w1S5H,iv:ZO6TqsGLYI6OTJ4SawB49xW/4FWQePNnCNfLNeFktIE=,tag:2fv/ixv4TArc2jsMgUzP4A==,type:comment]
    tag: ENC[AES256_GCM,data:6RU=,iv:NDCmbgohe/Na+srjNAmdEbxsO/XcAIpY+ePpcHJntj8=,tag:WMrALMfcnz5dh1DJecnXfg==,type:str]
postgresqlDbHost: ENC[AES256_GCM,data:6t1i/YDkyPWO+yjwI550,iv:S4O47KAP5ex8XrgXRV+wmp9ed8ZAceLCahQYV7GNf44=,tag:xhzFb5mPwYBqzXvkm4sw0w==,type:str]
imagePullSecrets:
    - name: ENC[AES256_GCM,data:2DgqDydyYc0j7Fv3sPqfCjWciA==,iv:jnJInf9YOBi09CbomhkiGii1aPnnPkuzCTn8kl6NX5k=,tag:h9bhyw6wVy3zEwS+WjY5aA==,type:str]
ingress:
    enabled: ENC[AES256_GCM,data:hRyR4w==,iv:+HyBvauE/A9NY85tY1PyF2M2Y8915lAAhVp053QYpfM=,tag:H6bNR6cn+Pnpe2oJejF/yg==,type:bool]
    annotations:
        kubernetes.io/ingress.class: ENC[AES256_GCM,data:gIR2WR8=,iv:rdZJWovBv6Hd0odwaD+LCJ7YNfFRuUFbklqUF1hKIx0=,tag:AIB1OkN4zpdfd8oly2ZGKw==,type:str]
        cert-manager.io/issuer: ENC[AES256_GCM,data:raJZfCSsNJjWDe4+ZPUWhbIADXo6XSL/,iv:AIWGutaBUgHQYxzfMku0WaYUoPW2TZYQ4ofOD1V9yEo=,tag:CPf3LBed05qoO5iQoRDslg==,type:str]
        cert-manager.io/issuer-kind: ENC[AES256_GCM,data:mNekANJ/pv5tWV/z,iv:clc7uZuQbsw1RFdqFmBf/7WD9vCCKC8OATiJTDNC748=,tag:lAmFJ2JDIZylMyidBrH5NQ==,type:str]
        cert-manager.io/issuer-group: ENC[AES256_GCM,data:cxobXpgHP17uWHQnP3t+yHFK19DnvJ9QYVY/WMpNcA==,iv:8RbCnQ91ulRU5wNH93tRSpkMp48tYhG5KQCBRh9kRyo=,tag:6vxas+Bfi/UPe+zCuArHEA==,type:str]
    hosts:
        - host: ENC[AES256_GCM,data:MxndnDwaOKXkFcGhQmO2T4VFJw==,iv:C4jCVWZMOkBwkSJxrV5pJqwnu9g4Vp0hjOBrh3oMmoI=,tag:fYmK64MgEoYVyjDgEvvBag==,type:str]
          paths:
            - path: ENC[AES256_GCM,data:Eg==,iv:hICL8Urs8U9oW0O1btuB4QGPXkhpbyrDD7L7Bw8L34c=,tag:dyB2I3ZmnRi+mv803Q987A==,type:str]
    tls:
        - hosts:
            - ENC[AES256_GCM,data:MZ+fnnv7vHtrhua8uDteQvmYSA==,iv:jrFFa/Jm1C86UohflidV5mbMyLca0FqxnzikSld14aM=,tag:sLK4PGDHjL78uA0YEODlJQ==,type:str]
          secretName: ENC[AES256_GCM,data:BdpE,iv:Tdxzv0XgT0dTT1vGQUWNveR/P11OcGuoH2M0uPGcO6Y=,tag:P76nEnxyDEZ/LJem7LZQLA==,type:str]
    https: ENC[AES256_GCM,data:3ttbFw==,iv:ia9QAoYB1F3ijBpQWYJTC4FlHPKLyQnymgug5Hd6PC4=,tag:fcJk9VOtoY+ugcpg40LqDg==,type:bool]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-24T04:40:20Z"
    mac: ENC[AES256_GCM,data:7TiP7gjB/SICVbssd37ObRq9Zh0M8KCqEcvumuHKWQxyBnCBs4f6NNzmcwD3VJ6OCCHenks9ZuCc5RQGPMzvu68yU57BLJOhmOF74yGyNFRuaB010i0YE5abS/gCeGrtrWNomYrMViNzewyxPTzR1dz0bYZAF1i2NxFyFzIsOc4=,iv:LJUqJhN2EDFmmtKMNgSHxYzCk1zn5S780a04Eph4X5Y=,tag:5cvSB4NluhlAhnLweWNZDw==,type:str]
    pgp:
        - created_at: "2021-09-26T18:21:49Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA6i3eDbXEFsmAQ/7BjroKcsoti6poswMyTmflfxczUsdXPwEWmQm6zetQjTy
            v4vvJBHTfdVv4AzoiYiBH9jYFNwbNx5+lkwKQqD+RztMW4s8xfrRWtRTLQI7RSse
            QP0mRQ3Zqe5ma2M4sjUxIbbEU03JAPtLR8lHuQLrlmBqGBTGz1m58dOG+kqEE065
            NMoXbwmvyvjyMoEEiO71B+CmMkZeK61VxeMJFQ6gKg15zUHrWqR7Wx+zXD4nzW2n
            8xgLWQj6JlvAocY/F/Avz33+ouUCsrtBARGW3myuJLBLermi5il8jcviovuYKCX8
            0OFFPZpy4eG1pcZnTriKNY2pOhAOhQUiHwYdhjgOdd2Mz9qw4WhWRK2RRk/yQjio
            F46cgjXUGoz4fAROCuQg2+nrV9+DxM3LqE9NHCEPW59VEZ/vjbl2n4lfR2fInqvt
            9slGgO7k+RhV5ySNdqR/BryHVld7Y30AAr4TrK3rPrxzMb7vvCyBZLetoGXKvTai
            O3Y8XgRygeo+cQYI/Hq70xqX/53awC7olkrMdiNsWQCWNYinn3MXFSmrnq+fkw2c
            QFO+BiOMyBHV42qwcxq8AAulHF1/l3QBYyynq7YOal83SICS/1E+Wd1wYf17j9kH
            cEmv62JtelqzSjox+Ar0oPOmH7MqVFzhsYRt7+iYm8RYuPhCwupJ77fIjkVEAZTS
            XgEZ2gOJvv1uRGV0cKBhIuUUMWMlCdcqqvxrNkbzlCcmHUKZxSt/v4yxAqKwMOBQ
            GEyJaczL54bGfBrXuIswtInukmJlXHGkYABTVXWrIcyGM8YE1vpNGL3kwqQMCps=
            =Qx7C
            -----END PGP MESSAGE-----
          fp: 3AEF4F9C947DF7F8F74844F3FD326D0D42804CE6
    unencrypted_suffix: _unencrypted
    version: 3.7.1
